Move code checks to pre-commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -16,4 +16,22 @@ fi
 printf "Running build runner to generate translation, chopper and moor files.\n"
 flutter pub run build_runner build
 
+printf "Running 'dart format'\n"
+files=$(find . \
+\( -name '*.dart' ! -name '*.i18n.dart' ! -name '*.g.dart' ! -name '*.chopper.dart' \) -print0 \
+ | xargs -0)
+
+if ! dart format -o none --fix --set-exit-if-changed $files
+then
+  printf "The above files need to be formatted.\n"
+  exit 1
+fi
+
+printf "Running 'dart analyze'\n"
+if ! dart analyze; then
+  printf "Error running 'dart analyze'\n"
+  exit 1
+fi
+printf "Finished running 'dart analyze'\n"
+
 exit 0
