Run integration tests on Codemagic

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -197,19 +197,12 @@ custom: # Custom properties to make workflows cleaner
         --build-number=$BUILD_NR \
         --dart-define BRAND=$BRAND \
         --dart-define SEGMENT_IOS_KEY=$SEGMENT_IOS_WRITE_KEY \
-    - &run_integration_tests
-      name: Run integration tests
+    - &run_integration_tests_android
+      name: Run integration tests on Android emulator
       script: |
         #!/usr/bin/env zsh
+        set -e # Ensures the script exits if any commands fail to execute
         sed -i -e '/SENTRY_DSN\=*/d' .env
-        wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-357.0.0-linux-x86_64.tar.gz
-        tar xf google-cloud-sdk-357.0.0-linux-x86_64.tar.gz
-        ./google-cloud-sdk/install.sh --quiet
-        source google-cloud-sdk/path.zsh.inc
-        echo "$GCLOUD_KEY" | base64 -d > gcloud-key.json
-        gcloud auth activate-service-account --key-file=gcloud-key.json
-        gcloud --quiet config set project vialer-fcm-423a9
-        gcloud components install alpha -q
         # Setup test vars
         sed -i -e "s/IN_TEST\=*/IN_TEST\=true/g" .env
         sed -i -e "s/TEST_USER_1_EMAIL\=*/TEST_USER_1_EMAIL\=$TEST_USER_1_EMAIL/g" .env
@@ -218,38 +211,11 @@ custom: # Custom properties to make workflows cleaner
         sed -i -e "s/TEST_USER_2_PASSWORD\=*/TEST_USER_2_PASSWORD\=$TEST_USER_2_PASSWORD/g" .env
         sed -i -e "s/TEST_USER_WITHOUT_APP_ACCOUNT_EMAIL\=*/TEST_USER_WITHOUT_APP_ACCOUNT_EMAIL\=$TEST_USER_WITHOUT_APP_ACCOUNT_EMAIL/g" .env
         sed -i -e "s/TEST_USER_WITHOUT_APP_ACCOUNT_PASSWORD\=*/TEST_USER_WITHOUT_APP_ACCOUNT_PASSWORD\=$TEST_USER_WITHOUT_APP_ACCOUNT_PASSWORD/g" .env
+        echo $ANDROID_FIREBASE_SECRET | base64 --decode > $FCI_BUILD_DIR/android/app/google-services.json
         setopt extended_glob
-        cd android
-        for filename in ../integration_test/tests/**/*.dart; do
-          # Although we're in a subdirectory, during building it uses paths relative to the project root.
-          filename=${filename#"../"}
-          pathname=${filename#"integration_test/"}
-          pathname=${pathname%".dart"}
-          ./gradlew app:assembleAndroidTest && ./gradlew app:assembleDebug -Ptarget="$filename"
-          echo "Starting test ${filename#"integration_test/tests/"}"
-          gcloud alpha firebase test android run --type=instrumentation --app=../build/app/outputs/apk/debug/app-debug.apk --test=../build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk --timeout=5m --results-bucket=vialer-fcm-423a9.appspot.com --results-dir="$FCI_BUILD_ID/$pathname" --quiet
-        done
-        cd ..
-        # iOS testing (disabled since it doesn't work)
-        #IOS_SDK=15.5
-        #keychain initialize
-        #app-store-connect fetch-signing-files $BUNDLE_ID \
-        #--type IOS_APP_STORE \
-        #--create
-        #keychain add-certificates
-        #xcode-project use-profiles
-        #flutter build ios --target integration_test/main.dart --release \
-        # --config-only \
-        #--export-options-plist=/Users/builder/export_options.plist \
-        #--verbose \
-        #--dart-define BRAND=$BRAND
-        #cd ios
-        #xcodebuild -workspace Runner.xcworkspace -scheme Runner -config Flutter/Release.xcconfig -derivedDataPath ../build/ios_integ -sdk iphoneos$IOS_SDK build-for-testing
-        #cd ..
-        #pushd build/ios_integ/Build/Products
-        #zip -r "ios_tests.zip" "Release-iphoneos" "Runner_iphoneos$IOS_SDK-arm64.xctestrun"
-        #popd
-        #gcloud firebase test ios run --test "build/ios_integ/Build/Products/ios_tests.zip" --device model=iphone13pro,version=15.2,locale=en_US,orientation=portrait
+        flutter emulators --launch emulator &
+        adb wait-for-device
+        . utils/test/run.sh
     - &update_gitlab_merge_request_with_build_url
       name: Updating the Merge Request in Gitlab with a link to this build
       script: |
@@ -475,12 +441,12 @@ workflows:
       - *flutter_pub_get
       - *analyze
       - *flutter_test
+      - *run_integration_tests_android
       - *build_aab
       - *build_universal_apk_from_aab
       - *update_ios_signing_for_current_brand
       - *build_ipa
       - *release_to_sentry
-      - *run_integration_tests
     triggering:
       events: [ ]
 
@@ -521,9 +487,7 @@ workflows:
       - *flutter_pub_get
       - *analyze
       - *flutter_test
-      - *build_aab
-      - *build_universal_apk_from_aab
-      - *run_integration_tests
+      - *run_integration_tests_android
     triggering:
       events: [ ]
 
