Scroll view

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -201,8 +201,7 @@ custom: # Custom properties to make workflows cleaner
       name: Run integration tests
       script: |
         #!/usr/bin/env zsh
-        # Make sure the script exits if any commands fail to execute
-        set -e
+        set -e # Ensures the script exits if any commands fail to execute
         dart utils/test/generate_single_integration_test_file.dart
         mkdir -p $HOME/bin && \
           curl https://maven.emulator.wtf/releases/ew-cli -o $HOME/bin/ew-cli && \
@@ -220,14 +219,19 @@ custom: # Custom properties to make workflows cleaner
         setopt extended_glob
         cd android
         ./gradlew app:assembleAndroidTest
-        ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/integration_test/tests/onboarding/login/login_success.dart"
-        ew-cli \
-          --app=../build/app/outputs/apk/debug/app-debug.apk \
-          --test=../build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
-          --timeout=30m \
-          --outputs-dir="$HOME/integration_test_output" \
-          --use-orchestrator \
-          --clear-package-data
+        for filename in ../integration_test/tests/**/*.dart; do
+          # Although we're in a subdirectory, during building it uses paths relative to the project root.
+          filename=${filename#"../"}
+          pathname=${filename#"integration_test/"}
+          pathname=${pathname%".dart"}
+          ./gradlew app:assembleDebug -Ptarget="$filename"
+          echo "Starting test ${filename#"integration_test/tests/"}"
+          ew-cli \
+            --app=../build/app/outputs/apk/debug/app-debug.apk \
+            --test=../build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
+            --timeout=5m \
+            --outputs-dir="$HOME/integration_test_output" \
+        done
         cd ..
     - &update_gitlab_merge_request_with_build_url
       name: Updating the Merge Request in Gitlab with a link to this build
